# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi_app', '0002_sitepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='locode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
