# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msi_app', '0003_auto_20181109_1533'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Port',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='port',
            new_name='location',
        ),
    ]
