# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msi_app', '0005_auto_20181109_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='locode',
        ),
    ]
