# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msi_app', '0010_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('serial', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Installed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now=True)),
                ('what', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msi_app.Hardware')),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msi_app.Location')),
            ],
        ),
    ]
