# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msi_app', '0012_auto_20181110_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installed',
            old_name='hardware',
            new_name='what',
        ),
    ]
