# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi_app', '0013_auto_20181110_0446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hardware',
            new_name='Component',
        ),
        migrations.AlterField(
            model_name='installed',
            name='when',
            field=models.DateTimeField(),
        ),
    ]
