# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msi_app', '0014_auto_20181110_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='name',
        ),
        migrations.AddField(
            model_name='node',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='msi_app.Component'),
            preserve_default=False,
        ),
    ]
