# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msi_app', '0021_auto_20181110_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='type',
            new_name='system',
        ),
    ]
