# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi_app', '0022_auto_20181110_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepicture',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_image'),
        ),
    ]
