# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi_app', '0024_auto_20181111_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='ipv4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='ipv6',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
