# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi_app', '0025_auto_20181111_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='ipv4',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='ipv6',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
    ]
